name: Update Locales

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: run update_locales.sh
      run: ./scripts/update_locales.sh
      
    - name: test3
      run: md2po "./README.md" -c -s --po-filepath "./readme2.po"
    - name: test4
      run: python -c "import os;print(os.path.exists('readme.po'));"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "locales: Automatic Update"
