name: Update Locales

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run update_locales.sh
      run: ./scripts/update_locales.sh

    - name: test
      run: md2po /home/runner/work/test-mdpo/test-mdpo/readme.md --md-encoding utf-8 --po-encoding utf-8 -e utf-8 -q -s -c --po-filepath /home/runner/work/test-mdpo/test-mdpo/readme.po

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "locales: Automatic Update"