name: Update Locales

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MDPO
      run: pip install mdpo
    - name: test1
      run: md2po ./README.md
    - name: test2
      run: python -c "import os;print(os.path.exists('readme.po'));"
    - name: test3
      run: cat ./README.md
