name: Update Locales

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MDPO
      run: pip install mdpo
    - name: generate file
      run: touch a.md
    - name: Insert Text
      run: echo "helloworld" >> a.md
    - name: test1
      run: md2po ./a.md
    - name: test2
      run: python -c "import os;print(os.path.exists('a.md'));"
    - name: test3
      run: cat ./a.md | md2po
    - name: test4
      run: cat ./a.md | md2po -s --po-filepath a.po && cat ./a.md | po2md -p a.po
    - name: test5
      run: cat ./a.md | md2po -s --po-filepath a.po && po2md a.md -p a.po
